apiVersion: v1
kind: Pod
metadata:
  name: access
  namespace: calico-policy-ns
  labels:
    app: access
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"
    tty: true
